version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-28-may-2024/luna-project/group-1:master
    command: 'sh /scripts/prod.sh'
    env_file:
      - ./env/prod.env
    depends_on:
      - postgres
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - frontend_build:/frontend/dist

  postgres:
    image: postgres:latest
    env_file:
      - ./env/prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - ./nginx:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend_build:/frontend_build


volumes:
  postgres_data:
  static_files:
  media_files:
  frontend_build: