# Generated by Django 5.0.6 on 2024-07-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
